### ISSUE TITLE
bug: running app without database requires custom health endpoint

### ISSUE THREAD

**Issue by peterschutt** [topsport-com-au/starlite-saqlalchemy#174]
The `db_session` dependency key is meant to be configurable (`APISettings.DB_SESSION_DEPENDENCY_KEY`), but the health check names it as `db_session` in its signature. 

We shouldn't be relying on dependency injection for this.

We should look for the session factory, wherever starlite puts it if the plugin is configured, and if it is there, use that to get a session for the check. If it isn't there, skip the check.

This will allow setting `do_sqlalchemy_plugin` to `False` when in an environment without a database.

**Comment by peterschutt** [comment]
I think i need the ability to write to app state via the plugin to do this properly.. e.g., seed app state with `check_db=False`.

**Comment by gazorby** [comment]
I use a custom healthcheck that does not require the `db_session` dependency:

```python
from dataclasses import asdict, dataclass
from typing import TYPE_CHECKING

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from starlite import Controller, HTTPException, get
from starlite_saqlalchemy import settings

if TYPE_CHECKING:
    from starlite import Router


@dataclass
class Ok:
    status: str = "ok"


@dataclass
class Ko:
    error: str
    status: str = "ko"


class HealthRouter(Controller):
    path: str = "/health"

    def __init__(self, owner: Router) -> None:
        super().__init__(owner)
        self.engine = create_async_engine(settings.db.URL, logging_name="health")
        self.Session = sessionmaker(
            bind=self.engine, class_=AsyncSession, expire_on_commit=False
        )

    @get("/live")
    async def live(self) -> Ok:
        return Ok()

    @get("/ready")
    async def ready(self) -> Ok:
        # Test database connection
        session = self.Session()
        try:
            await session.execute(text("SELECT * FROM information_schema.tables"))
        except Exception as error:
            raise HTTPException(503, asdict(Ko(error=str(error)))) from error
        await session.close()
        return Ok()
```

The other cool thing about instantiating a dedicated engine is that we can use a different `logging_name` from the main one so it's easier to exclude/distinguish those queries in logging.

**Comment by peterschutt** [comment]
Yes, good suggestion!

Do you use both `/health/live` and `/health/ready` for a database-backed application? Or do you use one or the other depending on the application?

**Comment by gazorby** [comment]
I use them to provide liveness/readiness probes in a k8s cluster.
Since liveness only indicates wether the container is running or not, I don't necessarily need the app to be connected to the db at this stage. Readiness tells the cluster that the app is ready to serve requests, which needs db access.

I mostly work on database-backed apis, but I suppose that in other cases my liveness check would be a readiness one.
