### ISSUE TITLE
Dependency extras

### ISSUE THREAD

**Issue by peterschutt** [topsport-com-au/starlite-saqlalchemy#211]
Any feature of the plugin that requires an additional dependency should require an "extra" install, and that feature should only be enabled if the extra is available.

For example, we make sentry an extra install, and we only configure it if it is available in the environment (and respecting the `PluginConfig.do_sentry` flag.

**Comment by gazorby** [comment]
Working on it. I just noticed that we have `hiredis` requirement but it's not import anywhere, any reason?

**Comment by peterschutt** [comment]
Thanks for picking this up! This is one that @cofin requested in starlite discord.

If `hiredis` is in the environment, it is automatically used by `redis-py`:

> For faster performance, install redis with hiredis support, this provides a compiled response parser, and for most cases requires zero code changes. By default, if hiredis >= 1.0 is available, redis-py will attempt to use it for response parsing.

**Comment by gazorby** [comment]
Alright, so we could create a "caching" dependency group with `redis` and `hiredis` what do you think?

**Comment by peterschutt** [comment]
Not sure - `redis` is a dependency of `saq` too - so not just for starlite caching.
