### ISSUE TITLE
feat(app): enable auto reloading if ENVIRONMENT == "local"

### ISSUE THREAD

**Issue by gazorby** [topsport-com-au/starlite-saqlalchemy#212]

**Comment by peterschutt** [comment]
There are already configs via environment that will enable auto-reloading, e.g., this is from my `.env` on a project I'm currently working on:

```.env
# Server
SERVER_HOST=localhost
SERVER_RELOAD=true
SERVER_RELOAD_DIRS='["."]'
```
Is that what you are looking for here, or something different?

**Comment by gazorby** [comment]
There is a typo in the title, I wonder if we can enable reloading when `ENVIRONEMENT` is set to `"local"`, as in most cases it's the desired behaviour.

**Comment by peterschutt** [comment]
Yep, I'm up for that. Maybe we change `ServerSettings.RELOAD` to `bool | None = None` and then in `scripts.run_app()`:

```python
uvicorn.run(
    ...
    reload=settings.server.RELOAD if settings.server.RELOAD is not None else settings.app.ENVIRONMENT == "local"
)
```

**Comment by peterschutt** [comment]
done in #231
