### ISSUE TITLE
bug: #219 doesn't allow for skipping cache/db readiness checks

### ISSUE THREAD

**Issue by peterschutt** [topsport-com-au/starlite-saqlalchemy#230]
#219 introduced a change to the `run-app` script where the database/cache readiness checks were moved into the before start lifespan hook in starlite.

This means that the args --no-db etc are no longer a part of the startup script, and therefore we no longer have a way to skip them.

Maybe we can just add configs to the plugin config object that allow them to be explicitly skipped.

**Comment by gazorby** [comment]
Isn't this solved by 76b5928e198b9ecad21a072fbd343b7586cf4bc9?

**Comment by peterschutt** [comment]
Yep, I should have closed this off!
