### ISSUE TITLE
Cannot import dto.factory

### ISSUE THREAD

**Issue by v3ss0n** [topsport-com-au/starlite-saqlalchemy#288]
from documentation this code won't work
`ReadDTO = dto.factory("AuthorReadDTO", Author, purpose=dto.Purpose.READ)`

There is no Factory  function in dto module , i  found it in pg starter so i had copied from there and it worked.
It suppose to be in dto module right?

**Comment by peterschutt** [comment]
This project has an alternate DTO implementation to `starlite`. If you are using this lib, see https://topsport-com-au.github.io/starlite-saqlalchemy/v0.29/dto/#configuring-generated-dtos.

I'm currently working on getting a similar pattern into starlite 2.0 as it addresses the static typing issues that the starlite 1.x implementation has. However that is a WIP.

After that is done, this lib will get a refactor around the starlite 2.0 patterns and the lib itself may be moved into the starlite org in some capacity, whether that is via starlite.contrib, or as a standalone lib.

**Comment by v3ss0n** [comment]
Right now i am building a starter project using this lib. So we should be using `WriteDTO = dto.FromMapped[Annotated[Author, dto.config("write")]]` this ?

**Comment by peterschutt** [comment]
Yep, let me know if you have any problems, but also be aware that there will likely be quite a bit of churn in this library over the coming weeks as starlite 2.0 gets finalised. This lib is still zero-ver, so there will likely still be breaking changes before it is stable.

**Comment by v3ss0n** [comment]
yes willing to help and test around and upgrade along with api changes , best way is to buiild something with it so i won't mind breaking changes , and will report.
