### ISSUE TITLE
bug(sentry): the sentry asgi middleware doesn't really work for us

### ISSUE THREAD

**Issue by peterschutt** [topsport-com-au/starlite-saqlalchemy#52]
Need to get the sentry integration task done for starlite org and use that instead.

**Comment by gazorby** [comment]
Integration is now availble with sdk [1.13.0](https://github.com/getsentry/sentry-python/releases/tag/1.13.0) released today ;) I think that we should get #213 first what do you think @peterschutt?

**Comment by peterschutt** [comment]
Yes saw this! Great stuff on that man. That sentry release removes the blocker for sqla RC2 as well!

> I think that we should get https://github.com/topsport-com-au/starlite-saqlalchemy/pull/213 first what do you think @peterschutt?

Yep agree totally. That'll be the task that will have the most code churn out of anything else I'd say, so would be good to get it out of the way before much else.

That's blocking on #174 right? I'll make sure the first review I do is #237, sound good?

**Comment by gazorby** [comment]
> That sentry release removes the blocker for sqla RC2 as well!
Nice !

> That's blocking on https://github.com/topsport-com-au/starlite-saqlalchemy/issues/174 right? I'll make sure the first review I do is https://github.com/topsport-com-au/starlite-saqlalchemy/pull/237, sound good?
Sounds good!
